version: '3.2'
services:
  nodejs:
    image: "node:latest"
    command: "npm test"
    volumes:
    - type: bind
      target: /app
      source: "."
    working_dir: /app

  r:
    build: "."
    volumes:
    - type: bind
      target: /home/rstudio/r4ds-exercise-solutions
      source: "."
    ports:
    - "8787:8787"
    working_dir: /home/rstudio/r4ds-exercise-solutions
