---
title: "Chapter 10"
author: "Marjorie Blanco"
date: "12/19/2018"
output: html_document
---

```{r setup, include=FALSE}
# Clear environment
rm(list = ls(all = TRUE))
knitr::opts_chunk$set(echo = FALSE, message=FALSE, error=FALSE, warning=FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

# Clear environment
rm(list = ls(all = TRUE))
library(wooldridge)
library(dplyr)
library(ggplot2)
library(stats)
```

## Example 10.1

```{r}
data('phillips')
```

```{r}
fit <- lm(inf~unem, data=phillips %>% filter(year < 1997))
summary(fit)
```

## Example 10.2

```{r}
data('intdef')
```

```{r}
fit <- lm(i3~inf+def, data=intdef)
summary(fit)
```

<!-- An increase in `mrate` is associated with a `r signif(abs(summary(fit)$coefficients["mrate", 1]), 3)` in the average `prate`  `r ifelse(summary(fit)$coefficients["mrate", 1] > 0, "increase", "decrease")` and this effect is  ``r ifelse(summary(fit)$coefficients["mrate", 4] < 0.05, "is", "is not")` statistically significant at 1%`. -->


## Example 10.3

```{r}
data('prminwge')
```

```{r}
fit <- lm(lprepop~lmincov+lusgnp, data=prminwge %>% filter(between(year, 1950, 1987)))
summary(fit)
```

## Example 10.4

```{r}
data('fertil3')
```

```{r}
fit <- lm(gfr~pe+ww2+pill, data=fertil3 %>% filter(between(year, 1913, 1984)))
summary(fit)
```
```{r}
fit <- lm(gfr~pe+pe_1+pe_2+ww2+pill, data=fertil3 %>% filter(between(year, 1913, 1984)))
summary(fit)
```

## Example 10.5

```{r}
data('barium')
```

```{r}
fit <- lm(lchnimp~lchempi+lgas+lrtwex+befile6+affile6+afdec6, data=barium)
summary(fit)
```

## Example 10.7

```{r}
data('hseinv')
```

```{r}
fit <- lm(linvpc~lprice, data=hseinv)
summary(fit)
```
```{r}
fit <- lm(linvpc~lprice+t, data=hseinv)
summary(fit)
```

## Example 10.8

```{r}
data('hseinv')
```

```{r}
fit <- lm(gfr~pe+ww2+pill+t, data=fertil3 %>% filter(between(year, 1913, 1984)))
summary(fit)
```

```{r}
fit <- lm(gfr~pe+ww2+pill+t+tsq, data=fertil3 %>% filter(between(year, 1913, 1984)))
summary(fit)
```

## Example 10.9

```{r}
fit <- lm(lprepop~lmincov+lusgnp+t, data=prminwge %>% filter(between(year, 1950, 1987)))
summary(fit)
```

## C1

```{r}
intdef <- intdef %>% mutate(y79 = year > 1979)
fit <- lm(i3~inf+def+y79, data=intdef)
summary(fit)
```

## C2

```{r}
fit <- lm(lchnimp~lchempi+lgas+lrtwex+befile6+affile6+afdec6, data=barium)
summary(fit)
fit <- lm(lchnimp~lchempi+lgas+lrtwex+befile6+affile6+afdec6+t, data=barium)
summary(fit)
```

```{r}
fit <- lm(lchnimp~lchempi+lgas+lrtwex+befile6+affile6+afdec6+t+feb+mar+apr+may+jun+jul+aug+sep+oct+nov+dec, data=barium)
summary(fit)
```

## C3

```{r}
fit <- lm(lprepop~lmincov+lusgnp+lprgnp+t, data=prminwge %>% filter(between(year, 1950, 1987)))
summary(fit)
```

## C4

```{r}

```

## C5


## C6

```{r}
fit <- lm(gfr~t+tsq, data=fertil3 %>% filter(between(year, 1913, 1984)))
summary(fit)
```


